In [35]:
import pandas as pd
import numpy as np

In [36]:
CSV_PATH = "/home/ori/Downloads/mnist_train.csv"

In [37]:
dfFull = pd.read_csv(CSV_PATH)
dfFull["label"] = dfFull["label"].astype("category")
label_one_hot = pd.get_dummies(dfFull["label"], prefix="label").astype(int)
df = pd.concat([dfFull, label_one_hot], axis=1)

In [38]:
df

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,label_0,label_1,label_2,label_3,label_4,label_5,label_6,label_7,label_8,label_9
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
59997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
59998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
59999,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [39]:
df_digit_1 =  df[df["label"] == 1]

In [40]:
df_digit_1

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,label_0,label_1,label_2,label_3,label_4,label_5,label_6,label_7,label_8,label_9
3,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59958,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59965,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59979,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59984,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59994,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [41]:
labels = np.array(["0","1","2","3","4","5","6","7","8","9"])

In [42]:
df_digit_1_norm = df_digit_1.drop("label", axis=1)

In [43]:
df_digit_1_norm

,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,1x10,...,label_0,label_1,label_2,label_3,label_4,label_5,label_6,label_7,label_8,label_9
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59958,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59965,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59979,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59984,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
59994,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [44]:
df_digit_1_norm.to_csv("/home/ori/Downloads/mnist_train_1.csv", index=False)

In [45]:
pd.read_csv("/home/ori/Downloads/mnist_train_1.csv")

,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,1x10,...,label_0,label_1,label_2,label_3,label_4,label_5,label_6,label_7,label_8,label_9
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6737,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6738,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6739,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6740,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6741,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0