In [45]:
import pandas as pd
import numpy as np

In [46]:
CSV_PATH = "/home/nerlnet/workspace/NErlNet/examples/mnistExample/mnist_train.csv"

In [47]:
pd.read_csv(CSV_PATH)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
dfFull = pd.read_csv(CSV_PATH)
dfFull["label"] = dfFull["label"].astype("category")
label_one_hot = pd.get_dummies(dfFull["label"], prefix="label").astype(int)
df = pd.concat([dfFull, label_one_hot], axis=1)

In [49]:
df

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,label_0,label_1,label_2,label_3,label_4,label_5,label_6,label_7,label_8,label_9
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
59997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
59998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
59999,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [50]:
df_digit_1 =  df[df["label"] == 4]

In [51]:
df_digit_1

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,label_0,label_1,label_2,label_3,label_4,label_5,label_6,label_7,label_8,label_9
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
26,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
53,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59933,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59941,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59943,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59951,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59975,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [52]:
df_digit_1_norm = df_digit_1.drop("label", axis=1)

In [53]:
df_digit_1_norm

,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,1x10,...,label_0,label_1,label_2,label_3,label_4,label_5,label_6,label_7,label_8,label_9
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
59997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
59998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
59999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [54]:
df_digit_1_norm.to_csv("/home/nerlnet/workspace/NErlNet/examples/mnistExample/mnist_train_temp.csv",header=False, index=False)

In [55]:
pd.read_csv("/home/nerlnet/workspace/NErlNet/examples/mnistExample/mnist_train_temp.csv")

,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.618,0.619,0.620,0.621,0.622,1.2,0.623,0.624,0.625,0.626
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
59996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
59997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
59998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0